### ISSUE TITLE
Problem with .S

### ISSUE THREAD

**Issue by wboeke** [potrepalov/forth#2]
In interpreting mode, the .S word does'nt work correctly. If I enter:
  s" aa" 
  s" bbb" 
  .s
then the output is:
  4261760 2 
  4261760 3
As you can see, the string adresses are equal. So the output of
  type space type
is
  bbb bb
If .S is used in compiled code, then there are no problems.

**Comment by potrepalov** [comment]
Hi!

Yes, and this is correct, especially: "Subsequent uses of S" may overwrite
the temporary buffer."

From DPANS:

11.6.1.2165 *S"*
*s-quote* FILE

Extend the semantics of 6.1.2165
<https://www.taygeta.com/forth/dpans6.htm#6.1.2165> S" to be:

        Interpretation: ( *"ccc<quote>"* -- c-addr u )

Parse ccc delimited by " (double quote). Store the resulting string c-addr
u at a temporary location. The maximum length of the temporary buffer is
implementation-dependent but shall be no less than 80 characters.
Subsequent uses of S" may overwrite the temporary buffer. At least one such
buffer shall be provided.

        Compilation: ( *"ccc<quote>"* -- )

Parse ccc delimited by " (double quote). Append the run-time semantics
given below to the current definition.

        Run-time: ( -- c-addr u )

Return c-addr and u that describe a string consisting of the characters ccc.


WBR, Ilia

чт, 18 апр. 2024 г. в 04:20, W.Boeke ***@***.***>:

**Comment by wboeke** [comment]
Indeed, legally you are right. However, I tried several forth's and most of them generate different addresses for different  S"..." .
I came across the issue when I wanted to assign different strings to different VALUE's (in interpreting mode). So using this forth that's not possible.
